kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Sales-Api
      - containerPort: 8000
        hostPort: 8000
      # Sales-Api debug
      - containerPort: 4000
        hostPort: 4000
      # Metrics
      - containerPort: 3001
        hostPort: 3001
      # Metrics debug
      - containerPort: 4001
        hostPort: 4001
      # Grafana
      - containerPort: 3100
        hostPort: 3100
      # Postgres
      - containerPort: 5432
        hostPort: 5431
      # Prometheus
      - containerPort: 9090
        hostPort: 9090
      # Tempo (tracing)
      - containerPort: 9411
        hostPort: 9411
